# Generated by Django 6.0.2 on 2026-02-26 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_incidents', models.PositiveIntegerField(default=0)),
                ('critical_incidents', models.PositiveIntegerField(default=0)),
                ('high_severity', models.PositiveIntegerField(default=0)),
                ('days_lost', models.PositiveIntegerField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-total_incidents'],
                'indexes': [models.Index(fields=['department', '-period_end'], name='analytics_d_departm_93cf22_idx')],
                'unique_together': {('department', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='SafetyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_work_hours', models.PositiveIntegerField(default=0, help_text='Total work hours for this period')),
                ('total_incidents', models.PositiveIntegerField(default=0)),
                ('lost_time_injuries', models.PositiveIntegerField(default=0)),
                ('near_misses', models.PositiveIntegerField(default=0)),
                ('total_days_lost', models.PositiveIntegerField(default=0)),
                ('total_hours_lost', models.PositiveIntegerField(default=0)),
                ('ltifr', models.FloatField(default=0.0, help_text='Lost Time Injury Frequency Rate')),
                ('trir', models.FloatField(default=0.0, help_text='Total Recordable Incident Rate')),
                ('severity_rate', models.FloatField(default=0.0, help_text='Average days lost per incident')),
                ('calculated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-period_end'],
                'indexes': [models.Index(fields=['-period_end'], name='analytics_s_period__0fe48c_idx'), models.Index(fields=['period_start', 'period_end'], name='analytics_s_period__bfddd6_idx')],
                'unique_together': {('period_start', 'period_end')},
            },
        ),
    ]
