# Generated by Django 6.0.2 on 2026-02-16 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CAPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, editable=False, help_text='Auto-generated reference (CAPA-YYYY-NNNNN)', max_length=50, unique=True)),
                ('action_type', models.CharField(choices=[('CORRECTIVE', 'Corrective Action - Fix the problem'), ('PREVENTIVE', 'Preventive Action - Prevent recurrence')], help_text='Corrective or Preventive?', max_length=20)),
                ('title', models.CharField(help_text='Brief description of the action', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of what needs to be done')),
                ('root_cause', models.TextField(blank=True, help_text='What caused the problem? (For preventive actions)')),
                ('due_date', models.DateField(help_text='When should this be completed?')),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], default=2, help_text='Priority level')),
                ('status', models.CharField(choices=[('OPEN', 'Open - Not started'), ('IN_PROGRESS', 'In Progress - Being worked on'), ('COMPLETED', 'Completed - Awaiting verification'), ('VERIFIED', 'Verified - Effectiveness confirmed'), ('CLOSED', 'Closed - Fully complete'), ('CANCELLED', 'Cancelled - No longer needed')], default='OPEN', help_text='Current status', max_length=20)),
                ('completion_date', models.DateField(blank=True, help_text='When was this actually completed?', null=True)),
                ('verification_date', models.DateField(blank=True, help_text='When was effectiveness verified?', null=True)),
                ('verification_notes', models.TextField(blank=True, help_text='Notes from verification/effectiveness check')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Who created this action?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_capas', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(help_text='The incident this action addresses', on_delete=django.db.models.deletion.CASCADE, related_name='capas', to='incidents.incident')),
                ('responsible_person', models.ForeignKey(help_text='Who is responsible for this action?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_capas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CAPA',
                'verbose_name_plural': 'CAPAs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='capas_capa_status_859d1d_idx'), models.Index(fields=['due_date'], name='capas_capa_due_dat_5a1e80_idx'), models.Index(fields=['priority'], name='capas_capa_priorit_06fd30_idx')],
            },
        ),
    ]
