# Generated by Django 6.0.2 on 2026-03-30 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capa',
            name='control_hierarchy',
            field=models.CharField(choices=[('ELIMINATION', 'Elimination - Remove the hazard'), ('SUBSTITUTION', 'Substitution - Replace the hazard'), ('ENGINEERING', 'Engineering - Isolate people from hazard'), ('ADMINISTRATIVE', 'Administrative - Change the way people work'), ('PPE', 'PPE - Protect worker with equipment')], default='ADMINISTRATIVE', help_text='Hierarchy of control level (ISO 45001 Requirement)', max_length=20),
        ),
    ]
