"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.28.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from decouple import config, Csv
try:
    from decouple import config as env
except ImportError:
    def env(key, default=''):
        return default

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', 'django-insecure-5ne5_m485%0^5falbeuc0-0!l%c+@ar(ymrc3&#-$hr*#%#93d')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG', default='True') == 'True'

ALLOWED_HOSTS = env('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',')


# Application definition


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    'rest_framework',
    #'rest_framework_simplejwt',
    'corsheaders',
    #'django_filters',
    #'drf_spectacular',
    #'django_celery_beat',
    # Our custom apps (HSE Management System)
    'users',              # User management extensions
    'incidents',          # Incident reporting and tracking
    'risk_assessment',    # Risk evaluation
    'capas',             # Corrective and Preventive Actions
    'evidence',          # File attachments (photos, documents)
    'notifications',     # Notification system
    'analytics',         # KPI calculations
]


MIDDLEWARE = [
    # 1. Security (always first)
    'django.middleware.security.SecurityMiddleware',
    
    # 2. Session
    'django.contrib.sessions.middleware.SessionMiddleware',
    
    # 3. CORS - MUST BE HERE, BEFORE CommonMiddleware!
    'corsheaders.middleware.CorsMiddleware',  # ← ADD THIS LINE
    
    # 4. Common
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================
# CUSTOM USER MODEL
# ============================================
#AUTH_USER_MODEL = 'users.User'

# ============================================
# REST FRAMEWORK
# ============================================
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}



# ============================================
# CORS
# ============================================
CORS_ALLOW_ALL_ORIGINS = DEBUG  # Allow all in dev
CORS_ALLOWED_ORIGINS = env('CORS_ALLOWED_ORIGINS', default='http://localhost:3000').split(',')

# ============================================
# CELERY
# ============================================
CELERY_BROKER_URL = env('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# ============================================
# DRF SPECTACULAR (API Docs)
# ============================================
SPECTACULAR_SETTINGS = {
    'TITLE': 'HSE Backend API',
    'DESCRIPTION': 'Health, Safety & Environment Management API',
    'VERSION': '1.0.0',
}

# ============================================
# MEDIA & STATIC
# ============================================
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# ============================================
# DJANGO REST FRAMEWORK CONFIGURATION
# ============================================

REST_FRAMEWORK = {
    # Authentication Classes
    # How users prove who they are
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # Session Authentication - Uses Django's session cookies
        # Good for: Browsable API, same-domain requests
        # How it works: Django sets a session cookie on login
        'rest_framework.authentication.SessionAuthentication',
        
        # Basic Authentication - Sends username/password with each request
        # Good for: Testing, development
        # How it works: Authorization: Basic base64(username:password)
        # ⚠️ Only use over HTTPS in production!
        'rest_framework.authentication.BasicAuthentication',
        
        # JWT Authentication - We'll add this in Part 4
        # 'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    
    # Permission Classes
    # Who can access what
    'DEFAULT_PERMISSION_CLASSES': [
        # IsAuthenticated - User must be logged in
        # Other options:
        # - AllowAny: Anyone can access (dangerous!)
        # - IsAdminUser: Only staff users
        # - IsAuthenticatedOrReadOnly: Login required for write, anyone can read
        'rest_framework.permissions.IsAuthenticated',
    ],
    
    # Pagination
    # Limit number of results per page
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    
    # Why pagination?
    # Without: GET /api/incidents/ returns ALL incidents (could be 10,000!)
    # With: Returns 20 incidents + links to next/previous pages
    #
    # Response format:
    # {
    #   "count": 153,
    #   "next": "http://api.example.com/incidents/?page=2",
    #   "previous": null,
    #   "results": [... 20 incidents ...]
    # }
    
    # Filtering, Searching, Ordering
    'DEFAULT_FILTER_BACKENDS': [
        # DjangoFilterBackend - Filter by field values
        # Example: /api/incidents/?status=SUBMITTED&severity=HIGH
        'django_filters.rest_framework.DjangoFilterBackend',
        
        # SearchFilter - Full-text search
        # Example: /api/incidents/?search=warehouse
        # Searches in fields you specify (title, description, etc.)
        'rest_framework.filters.SearchFilter',
        
        # OrderingFilter - Sort results
        # Example: /api/incidents/?ordering=-incident_date
        # - (minus) = descending, no prefix = ascending
        'rest_framework.filters.OrderingFilter',
    ],
    
    # Response Renderers
    # How to format the output
    'DEFAULT_RENDERER_CLASSES': [
        # JSONRenderer - Returns JSON (for React, mobile apps)
        'rest_framework.renderers.JSONRenderer',
        
        # BrowsableAPIRenderer - Nice HTML interface for testing
        # You can test your API directly in the browser!
        # ⚠️ Disable in production (security)
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    
    # Request Parsers
    # What content types can the API accept?
    'DEFAULT_PARSER_CLASSES': [
        # JSONParser - application/json (most common)
        'rest_framework.parsers.JSONParser',
        
        # FormParser - application/x-www-form-urlencoded
        # For HTML forms
        'rest_framework.parsers.FormParser',
        
        # MultiPartParser - multipart/form-data
        # For file uploads
        'rest_framework.parsers.MultiPartParser',
    ],
    
    # Date/Time Format
    # ISO 8601 standard
    'DATETIME_FORMAT': '%Y-%m-%dT%H:%M:%SZ',
    # Example: 2026-02-15T14:30:00Z
    
    # Exception Handler
    # How errors are formatted
    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',
}

# What does each setting do?
# 
# AUTHENTICATION:
# - Identifies who the user is
# - Session: Uses cookies (like regular Django)
# - Basic: Sends username/password (insecure without HTTPS)
# - JWT: Stateless tokens (we'll add this later)
# 
# PERMISSIONS:
# - Controls what users can do
# - IsAuthenticated: Must be logged in
# - Can customize per view
# 
# PAGINATION:
# - Prevents loading thousands of records
# - Improves performance
# - Better UX
# 
# FILTERING:
# - DjangoFilterBackend: ?status=OPEN
# - SearchFilter: ?search=warehouse
# - OrderingFilter: ?ordering=-created_at
# 
# RENDERERS:
# - JSON: For APIs (React, mobile)
# - Browsable: For testing in browser
# config/settings.py (scroll to bottom and add)

# ============================================
# CORS (Cross-Origin Resource Sharing) CONFIGURATION
# ============================================

# Development: Allow requests from React development servers
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",      # Create React App default port
    "http://localhost:5173",      # Vite default port
    "http://127.0.0.1:3000",     # Alternative localhost
    "http://127.0.0.1:5173",     # Alternative localhost
]

# Why multiple origins?
# - Different tools use different ports
# - Some browsers/tools use localhost, others use 127.0.0.1
# - Better to be permissive in development
# - In production, we'll use only our actual domain

# Allow credentials (cookies, authorization headers)
CORS_ALLOW_CREDENTIALS = True

# Why True?
# - Allows cookies to be sent cross-origin
# - Allows Authorization headers
# - Required for session auth and JWT
# - Must be True if using authentication

# Allowed HTTP methods
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# These are the standard REST methods
# OPTIONS is for preflight requests (browser checks before actual request)

# Allowed headers
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Important headers explained:
# - authorization: For JWT tokens (Bearer <token>)
# - content-type: Tells server what format data is in (application/json)
# - x-csrftoken: For CSRF protection
# - origin: Browser automatically adds this

# Alternative for development (easier but less secure):
# CORS_ALLOW_ALL_ORIGINS = True  # ⚠️ NEVER use in production!
# 
# Why not use this?
# - Opens your API to ANY website
# - Security risk
# - Only OK for public APIs with no authentication
# - Always specify exact origins in production

# Production configuration (example - we'll use this later):
# if not DEBUG:
#     CORS_ALLOWED_ORIGINS = [
#         "https://yourdomain.com",
#         "https://www.yourdomain.com",
#     ]
#     CORS_ALLOW_ALL_ORIGINS = False
