"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.28.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from decouple import config, Csv
try:
    from decouple import config as env
except ImportError:
    def env(key, default=''):
        return default

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', 'django-insecure-5ne5_m485%0^5falbeuc0-0!l%c+@ar(ymrc3&#-$hr*#%#93d')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG', default='True') == 'True'

ALLOWED_HOSTS = env('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',')

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django_filters',
    'drf_spectacular',
    'django_celery_beat',
    'django_celery_results',
    
    #custom apps (HSE Management System)
    'users',              
    'incidents',          
    'risk_assessment',    
    'capas',             
    'evidence',          
    'notifications',     
    'analytics',         
]


MIDDLEWARE = [
    # 1. Security 
    'django.middleware.security.SecurityMiddleware',
    
    # 2. Session
    'django.contrib.sessions.middleware.SessionMiddleware',
    
    # 3. CORS - MUST BE BEFORE CommonMiddleware!
    'corsheaders.middleware.CorsMiddleware',  # ← ADD THIS LINE
    
    # 4. Common
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'



DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

# Default primary key field type

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================
# CUSTOM USER MODEL
# ============================================
#AUTH_USER_MODEL = 'users.User'

# ============================================
# DJANGO REST FRAMEWORK CONFIGURATION
# ============================================
REST_FRAMEWORK = {
    # Authentication & Permissions
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    
    # Schema Generation (THIS WAS BEING OVERWRITTEN)
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    
    # Pagination
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    
    # Filtering, Searching, Ordering
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
    
    # Renderers and Parsers
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    
    # Formats
    'DATETIME_FORMAT': '%Y-%m-%dT%H:%M:%SZ',
}



# ============================================
# CORS
# ============================================
CORS_ALLOW_ALL_ORIGINS = DEBUG  # Allow all in dev
CORS_ALLOWED_ORIGINS = env('CORS_ALLOWED_ORIGINS', default='http://localhost:3000').split(',')

# ============================================
# CELERY
# ============================================
CELERY_BROKER_URL = env('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# ============================================
# DRF SPECTACULAR (API Docs)
# ============================================
SPECTACULAR_SETTINGS = {
    'TITLE': 'HSE Backend API',
    'DESCRIPTION': 'Health, Safety & Environment Management API',
    'VERSION': '1.0.0',
}

# ============================================
# MEDIA & STATIC
# ============================================
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# What does each setting do?
# 
# AUTHENTICATION:
# - Identifies who the user is
# - Session: Uses cookies 
# - Basic: Sends username/password (insecure without HTTPS)
# - JWT: Stateless tokens 
# 
# PERMISSIONS:
# - Controls what users can do
# - IsAuthenticated: Must be logged in
# - Can customize per view
# 
# PAGINATION:
# - Prevents loading thousands of records
# - Improves performance
# - Better UX
# 
# FILTERING:
# - DjangoFilterBackend: ?status=OPEN
# - SearchFilter: ?search=warehouse
# - OrderingFilter: ?ordering=-created_at
# 
# RENDERERS:
# - JSON: For APIs (React, mobile)
# - Browsable: For testing in browser
# config/settings.py (scroll to bottom and add)

# ============================================
# CORS (Cross-Origin Resource Sharing) CONFIGURATION
# ============================================

# Development: Allow requests from React development servers
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",      # Create React App default port
    "http://localhost:5173",      # Vite default port
    "http://127.0.0.1:3000",     # Alternative localhost
    "http://127.0.0.1:5173",     # Alternative localhost
]

# Why multiple origins?
# - Different tools use different ports
# - Some browsers/tools use localhost, others use 127.0.0.1
# - Better to be permissive in development
# - In production, we'll use only our actual domain

# Allow credentials (cookies, authorization headers)
CORS_ALLOW_CREDENTIALS = True

# Why True?
# - Allows cookies to be sent cross-origin
# - Allows Authorization headers
# - Required for session auth and JWT
# - Must be True if using authentication

# Allowed HTTP methods
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# These are the standard REST methods
# OPTIONS is for preflight requests

# Allowed headers
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Important headers explained:
# - authorization: For JWT tokens (Bearer <token>)
# - content-type: Tells server what format data is in (application/json)
# - x-csrftoken: For CSRF protection
# - origin: Browser automatically adds this

# Alternative for development (easier but less secure):
# CORS_ALLOW_ALL_ORIGINS = True  # ⚠️ NEVER use in production!
# 
# Why not use this?
# - Opens your API to ANY website
# - Security risk
# - Only OK for public APIs with no authentication
# - Always specify exact origins in production

# Production configuration (example - we'll use this later):
# if not DEBUG:
#     CORS_ALLOWED_ORIGINS = [
#         "https://yourdomain.com",
#         "https://www.yourdomain.com",
#     ]
#     CORS_ALLOW_ALL_ORIGINS = False


# ============================================
# MEDIA FILES (User Uploads)
# ============================================

# URL that handles the media served from MEDIA_ROOT
MEDIA_URL = '/media/'

# Absolute filesystem path to the directory that will hold user-uploaded files
MEDIA_ROOT = BASE_DIR / 'media'

# Why separate STATIC vs MEDIA?
# STATIC_URL = '/static/'    → Your CSS, JS, images (part of your code)
# STATIC_ROOT = ...          → Collected static files for production
# 
# MEDIA_URL = '/media/'      → User uploads (photos, documents, etc.)
# MEDIA_ROOT = ...           → Where uploads are stored
# 
# STATIC files: version controlled, same for all users
# MEDIA files: NOT in Git, different for each deployment

# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10 MB
# Files larger than this are streamed to disk instead of memory
# Prevents large uploads from consuming too much RAM

DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10 MB
# Maximum size of request body
# Prevents denial-of-service via huge uploads

# Allowed file extensions (for security)
ALLOWED_UPLOAD_EXTENSIONS = [
    # Images
    '.jpg', '.jpeg', '.png', '.gif', '.bmp', '.svg', '.webp',
    # Documents
    '.pdf', '.doc', '.docx', '.xls', '.xlsx', '.ppt', '.pptx',
    '.txt', '.csv', '.rtf', '.odt', '.ods', '.odp',
    # Archives
    '.zip', '.rar', '.7z', '.tar', '.gz',
    # Videos (if needed)
    '.mp4', '.avi', '.mov', '.wmv', '.flv', '.mkv',
]

# Maximum file size (50 MB)
MAX_UPLOAD_SIZE = 50 * 1024 * 1024  # 50 MB in bytes

# Why these limits?
# - Prevent abuse (users uploading huge files)
# - Server storage management
# - Performance (large files slow down uploads)
# - Security (limit attack surface)

# ============================================
# DRF SPECTACULAR (API DOCUMENTATION)
# ============================================

SPECTACULAR_SETTINGS = {
    'TITLE': 'HSE Management System API',
    'DESCRIPTION': '''
    Health, Safety & Environment Management System API
    
    This API provides comprehensive endpoints for managing:
    - Incident reporting and tracking
    - Risk assessments
    - Corrective and Preventive Actions (CAPAs)
    - Evidence and file uploads
    - Notifications
    - Analytics and KPIsAuthentication: JWT Bearer Token
    ''',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    
    # Swagger UI settings
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': True,
    },
    # Authentication
    'SECURITY': [
        {
            'Bearer': {
                'type': 'http',
                'scheme': 'bearer',
                'bearerFormat': 'JWT',
            }
        }
    ],
}
# ============================================
# CELERY CONFIGURATION
# ============================================

# Redis as message broker
CELERY_BROKER_URL = 'redis://localhost:6379/0'

# Store results in Redis
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'

# Or store results in database:
#CELERY_RESULT_BACKEND = 'django-db'

# Task serialization
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# Timezone
CELERY_TIMEZONE = 'UTC'

# Task result expiration (7 days)
CELERY_RESULT_EXPIRES = 60 * 60 * 24 * 7

# Task time limit (10 minutes max)
CELERY_TASK_TIME_LIMIT = 10 * 60

# Task soft time limit (warning at 9 minutes)
CELERY_TASK_SOFT_TIME_LIMIT = 9 * 60

# Task routing
CELERY_TASK_ROUTES = {
    'incidents.tasks.*': {'queue': 'incidents'},
    'notifications.tasks.*': {'queue': 'notifications'},
}


from celery.schedules import crontab

# config/settings.py (update CELERY_BEAT_SCHEDULE)

CELERY_BEAT_SCHEDULE = {
    # Daily report at 8 AM
    'daily-incident-report': {
        'task': 'incidents.tasks.generate_daily_incident_report',
        'schedule': crontab(hour=8, minute=0),
    },
    
    # Weekly summary every Monday at 9 AM
    'weekly-summary': {
        'task': 'incidents.tasks.send_weekly_summary',
        'schedule': crontab(day_of_week=1, hour=9, minute=0),
    },
    
    # Check overdue every hour
    'check-overdue-incidents': {
        'task': 'incidents.tasks.check_overdue_incidents',
        'schedule': crontab(minute=0),
    },
    
    # Escalate critical every 30 minutes
    'escalate-critical': {
        'task': 'incidents.tasks.escalate_critical_incidents',
        'schedule': crontab(minute='*/30'),
    },
    
    # Monthly metrics on 1st at midnight
    'monthly-safety-metrics': {
        'task': 'incidents.tasks.calculate_safety_metrics',
        'schedule': crontab(day_of_month=1, hour=0, minute=0),
    },
    
    # Cleanup old incidents on 1st at 2 AM
    'cleanup-old-incidents': {
        'task': 'incidents.tasks.cleanup_old_incidents',
        'schedule': crontab(day_of_month=1, hour=2, minute=0),
    },
    
    # FOR TESTING: Every 2 minutes
    'test-task-every-2-min': {
        'task': 'incidents.tasks.check_overdue_incidents',
        'schedule': crontab(minute='*/2'),  # Every 2 minutes
    },
}
# ============================================
# EMAIL CONFIGURATION
# ============================================
# En mode développement, on affiche les emails dans la console
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#DEFAULT_FROM_EMAIL = 'admin@hse.local'
#EMAIL_HOST = 'smtp.mailtrap.io'
# Looking to send emails in production? Check out our Email API/SMTP product!
#EMAIL_HOST = 'sandbox.smtp.mailtrap.io'
#EMAIL_HOST_USER = 'c3f38744d6a12b'
#EMAIL_HOST_PASSWORD = 'be10d56099b022'
#EMAIL_PORT = '2525'
#EMAIL_USE_TLS = True


from decouple import config

# ============================================
# EMAIL CONFIGURATION (Gmail)
# ============================================

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# Load from environment variables
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='hse-system@example.com')

# Additional settings
EMAIL_TIMEOUT = 10  # Timeout in seconds