# Generated by Django 6.0.2 on 2026-02-16 23:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('incident', models.OneToOneField(help_text='The incident being assessed', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='risk_assessment', serialize=False, to='incidents.incident')),
                ('probability', models.IntegerField(choices=[(1, 'Very Unlikely - Rare occurrence (< 1%)'), (2, 'Unlikely - Could happen (1-10%)'), (3, 'Possible - Might happen (10-50%)'), (4, 'Likely - Probably will happen (50-90%)'), (5, 'Almost Certain - Expected to occur (> 90%)')], help_text='Likelihood of recurrence (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('impact', models.IntegerField(choices=[(1, 'Negligible - No injury, minimal damage'), (2, 'Minor - First aid, minor damage'), (3, 'Moderate - Medical treatment, significant damage'), (4, 'Major - Hospitalization, extensive damage'), (5, 'Catastrophic - Fatality, disaster')], help_text='Severity of consequences (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('risk_level', models.IntegerField(editable=False, help_text='Calculated: Probability × Impact (1-25)')),
                ('risk_category', models.CharField(editable=False, help_text='Category: Very Low, Low, Medium, High, Critical', max_length=20)),
                ('existing_controls', models.TextField(blank=True, help_text='What controls are currently in place?')),
                ('recommended_controls', models.TextField(blank=True, help_text='What additional controls are recommended?')),
                ('assessment_notes', models.TextField(blank=True, help_text='Additional notes or considerations')),
                ('assessed_date', models.DateTimeField(auto_now_add=True, help_text='When was this assessment performed?')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessed_by', models.ForeignKey(help_text='Who performed this assessment?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Risk Assessment',
                'verbose_name_plural': 'Risk Assessments',
                'ordering': ['-risk_level'],
            },
        ),
    ]
