# Generated by Django 6.0.2 on 2026-02-17 01:23

import django.db.models.deletion
import evidence.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(help_text='ID of the object this evidence is attached to')),
                ('file', models.FileField(help_text='The uploaded file', upload_to=evidence.models.evidence_upload_path, validators=[evidence.models.validate_file_extension, evidence.models.validate_file_size])),
                ('file_type', models.CharField(choices=[('PHOTO', 'Photo/Image'), ('DOCUMENT', 'Document'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('OTHER', 'Other')], help_text='Type of file', max_length=20)),
                ('title', models.CharField(blank=True, help_text='Optional title/description of the file', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional detailed description')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='When was this file uploaded?')),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('content_type', models.ForeignKey(help_text='Type of object this evidence is attached to', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('uploaded_by', models.ForeignKey(help_text='Who uploaded this file?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evidence',
                'verbose_name_plural': 'Evidence',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='evidence_ev_content_7eb115_idx'), models.Index(fields=['uploaded_at'], name='evidence_ev_uploade_01a06d_idx'), models.Index(fields=['file_type'], name='evidence_ev_file_ty_83013b_idx')],
            },
        ),
    ]
