# Generated by Django 6.0.2 on 2026-02-15 21:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, editable=False, help_text='Auto-generated reference number (INC-YYYY-NNNNN)', max_length=50, unique=True)),
                ('title', models.CharField(help_text='Brief description of the incident (max 200 characters)', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of what happened')),
                ('incident_type', models.CharField(choices=[('ACCIDENT', 'Accident'), ('NEAR_MISS', 'Near Miss'), ('UNSAFE_CONDITION', 'Unsafe Condition'), ('ENVIRONMENTAL', 'Environmental Incident')], help_text='Type of incident', max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Low - Minor injury, no time lost'), ('MEDIUM', 'Medium - Medical treatment, limited time lost'), ('HIGH', 'High - Significant injury, extended time lost'), ('CRITICAL', 'Critical - Fatality or permanent disability')], default='LOW', help_text='Severity level of the incident', max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_INVESTIGATION', 'Under Investigation'), ('VALIDATED', 'Validated'), ('CLOSED', 'Closed')], default='DRAFT', help_text='Current status in the workflow', max_length=30)),
                ('incident_date', models.DateTimeField(help_text='When did the incident occur?')),
                ('location', models.CharField(help_text="Where did the incident occur? (e.g., 'Warehouse A, Zone 3')", max_length=200)),
                ('department', models.CharField(help_text="Which department? (e.g., 'Production', 'Maintenance')", max_length=100)),
                ('injuries', models.TextField(blank=True, help_text='Description of any injuries sustained', null=True)),
                ('property_damage', models.TextField(blank=True, help_text='Description of property/equipment damage', null=True)),
                ('work_hours_lost', models.PositiveIntegerField(default=0, help_text='Total work hours lost due to incident', validators=[django.core.validators.MinValueValidator(0)])),
                ('days_lost', models.PositiveIntegerField(default=0, help_text='Total work days lost due to incident', validators=[django.core.validators.MinValueValidator(0)])),
                ('reported_date', models.DateTimeField(auto_now_add=True, help_text='When was this incident reported?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Who is investigating this incident?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(help_text='Who reported this incident?', on_delete=django.db.models.deletion.PROTECT, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
                'ordering': ['-incident_date'],
                'permissions': [('can_validate_incident', 'Can validate incidents'), ('can_assign_incident', 'Can assign incidents to investigators'), ('can_close_incident', 'Can close incidents')],
                'indexes': [models.Index(fields=['incident_date'], name='incidents_i_inciden_663685_idx'), models.Index(fields=['status'], name='incidents_i_status_9a4f12_idx'), models.Index(fields=['severity'], name='incidents_i_severit_10e3a5_idx'), models.Index(fields=['department'], name='incidents_i_departm_5d4134_idx'), models.Index(fields=['-incident_date', 'status'], name='incidents_i_inciden_a7058e_idx')],
            },
        ),
    ]
