# Generated by Django 6.0.2 on 2026-03-30 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Estimated financial impact (Direct + Indirect)', max_digits=12),
        ),
        migrations.AddField(
            model_name='incident',
            name='root_cause_category',
            field=models.CharField(blank=True, choices=[('HUMAN_ERROR', 'Human Error / Unsafe Act'), ('EQUIPMENT_FAILURE', 'Equipment/Tool Failure'), ('PROCESS_GAP', 'Process/Procedure Gap'), ('ENVIRONMENTAL_FACTOR', 'External/Environmental Factor'), ('MANAGEMENT_FAILURE', 'Management/Supervisory Failure'), ('TRAINING_GAP', 'Lack of Training/Competence')], help_text='Categorization for root cause analysis', max_length=50),
        ),
        migrations.AddField(
            model_name='incident',
            name='root_cause_description',
            field=models.TextField(blank=True, help_text='Detailed investigation findings and 5-Whys summary'),
        ),
    ]
