# Generated by Django 6.0.2 on 2026-03-31 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_incident_estimated_cost_incident_root_cause_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='has_property_damage',
            field=models.BooleanField(default=False, help_text='Was there any damage to property or equipment?'),
        ),
    ]
