# Generated by Django 6.0.2 on 2026-02-17 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('INCIDENT_CREATED', 'Incident Created'), ('INCIDENT_ASSIGNED', 'Incident Assigned to You'), ('INCIDENT_VALIDATED', 'Incident Validated'), ('INCIDENT_CLOSED', 'Incident Closed'), ('CAPA_CREATED', 'CAPA Created'), ('CAPA_ASSIGNED', 'CAPA Assigned to You'), ('CAPA_DUE_SOON', 'CAPA Due Soon'), ('CAPA_OVERDUE', 'CAPA Overdue'), ('CAPA_COMPLETED', 'CAPA Completed'), ('RISK_HIGH', 'High Risk Identified'), ('RISK_CRITICAL', 'Critical Risk Identified'), ('SYSTEM', 'System Notification')], help_text='Type of notification', max_length=30)),
                ('title', models.CharField(help_text='Notification title', max_length=200)),
                ('message', models.TextField(help_text='Notification message')),
                ('link', models.CharField(blank=True, help_text='Link to related object (e.g., /incidents/1/)', max_length=500)),
                ('is_read', models.BooleanField(default=False, help_text='Has the user read this notification?')),
                ('read_at', models.DateTimeField(blank=True, help_text='When was this notification read?', null=True)),
                ('email_sent', models.BooleanField(default=False, help_text='Was an email sent for this notification?')),
                ('email_sent_at', models.DateTimeField(blank=True, help_text='When was the email sent?', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When was this notification created?')),
                ('recipient', models.ForeignKey(help_text='Who receives this notification?', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['recipient', 'created_at'], name='notificatio_recipie_f39341_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx')],
            },
        ),
    ]
